/**
 * Single-File Export Generator
 *
 * Produces a complete, standalone .tsx file string from rawCode.
 * The output includes React + Remotion imports, the user's component,
 * a Composition wrapper, and registerRoot — ready to run with
 * `npx remotion render`.
 */

import { detectUsedAPIs, extractMetadata } from "./export-utils";

/**
 * Options for generating an export file.
 */
export interface ExportOptions {
  /** Raw JSX code without imports (as stored in the database) */
  rawCode: string;
  /** The user's original prompt text */
  prompt: string;
  /** Duration of the composition in frames */
  durationInFrames: number;
  /** Frames per second */
  fps: number;
}

/**
 * Generate a complete standalone .tsx file string.
 *
 * The output file includes:
 * 1. Header comments (Generated by RemotionLab + prompt)
 * 2. React import
 * 3. Remotion imports (auto-detected from code + scaffold APIs)
 * 4. The user's component code (metadata comments stripped)
 * 5. RemotionRoot with Composition wrapper
 * 6. registerRoot call
 *
 * @param options - Export configuration including rawCode, prompt, and timing
 * @returns Complete .tsx file content as a string
 */
export function generateSingleFile(options: ExportOptions): string {
  const { rawCode, prompt, durationInFrames, fps } = options;

  // Detect which Remotion APIs are used in the code
  const usedAPIs = detectUsedAPIs(rawCode);

  // Strip metadata comments from the code body
  const { cleanedCode } = extractMetadata(rawCode);

  // Combine detected APIs with scaffold APIs (always needed for the wrapper)
  const scaffoldAPIs = ["Composition", "registerRoot"];
  const allAPIs = [...new Set([...usedAPIs, ...scaffoldAPIs])].sort();

  // Escape double quotes in prompt for the comment
  const escapedPrompt = prompt.replace(/"/g, '\\"');

  // Build the Remotion import list (one per line for readability)
  const remotionImportList = allAPIs.map((api) => `  ${api},`).join("\n");

  return `// Generated by RemotionLab
// Prompt: "${escapedPrompt}"

import React from "react";
import {
${remotionImportList}
} from "remotion";

${cleanedCode}

export const RemotionRoot: React.FC = () => {
  return (
    <Composition
      id="MyComposition"
      component={MyComposition}
      durationInFrames={${durationInFrames}}
      fps={${fps}}
      width={1920}
      height={1080}
    />
  );
};

registerRoot(RemotionRoot);
`;
}
