/**
 * Project Zip Export Generator
 *
 * Produces a complete Remotion project scaffold as a zip Blob.
 * The zip contains 6 files in a `remotionlab-export/` folder:
 *   - src/MyComposition.tsx  (user's component with imports and export)
 *   - src/Root.tsx           (Composition setup)
 *   - src/index.ts           (entry point with registerRoot)
 *   - package.json           (Remotion + React dependencies)
 *   - tsconfig.json          (TypeScript configuration)
 *   - remotion.config.ts     (Remotion CLI configuration)
 *
 * The resulting zip is a runnable Remotion project — just unzip,
 * `npm install`, and `npm run dev`.
 */

import JSZip from "jszip";
import { detectUsedAPIs, extractMetadata } from "./export-utils";
import type { ExportOptions } from "./export-single-file";

export type { ExportOptions } from "./export-single-file";

/**
 * Generate a zip Blob containing a complete Remotion project scaffold.
 *
 * @param options - Export configuration including rawCode, prompt, and timing
 * @returns Promise resolving to a zip Blob
 */
export async function generateProjectZip(
  options: ExportOptions
): Promise<Blob> {
  const { rawCode, prompt, durationInFrames, fps } = options;

  // Detect which Remotion APIs are used in the code
  const usedAPIs = detectUsedAPIs(rawCode);

  // Strip metadata comments from the code body
  const { cleanedCode } = extractMetadata(rawCode);

  // Escape double quotes in prompt for the comment
  const escapedPrompt = prompt.replace(/"/g, '\\"');

  // Build file contents
  const componentContent = generateComponentFile(
    usedAPIs,
    cleanedCode,
    escapedPrompt
  );
  const rootContent = generateRootFile(durationInFrames, fps);
  const indexContent = generateIndexFile();
  const packageJsonContent = generatePackageJson();
  const tsconfigContent = generateTsConfig();
  const remotionConfigContent = generateRemotionConfig();

  // Assemble zip
  const zip = new JSZip();
  const root = zip.folder("remotionlab-export")!;
  const src = root.folder("src")!;

  src.file("MyComposition.tsx", componentContent);
  src.file("Root.tsx", rootContent);
  src.file("index.ts", indexContent);
  root.file("package.json", packageJsonContent);
  root.file("tsconfig.json", tsconfigContent);
  root.file("remotion.config.ts", remotionConfigContent);

  return zip.generateAsync({ type: "blob" });
}

/**
 * Generate MyComposition.tsx — the user's component with imports and export keyword.
 * Does NOT include Composition or registerRoot (those live in Root.tsx and index.ts).
 */
function generateComponentFile(
  usedAPIs: string[],
  cleanedCode: string,
  escapedPrompt: string
): string {
  // Build Remotion imports (only APIs used in code, sorted)
  const remotionImportList = usedAPIs.map((api) => `  ${api},`).join("\n");

  // Add export keyword to the component declaration
  const exportedCode = cleanedCode.replace(
    /^const MyComposition/m,
    "export const MyComposition"
  );

  // Build Remotion import block only if there are APIs to import
  const remotionImportBlock =
    usedAPIs.length > 0
      ? `import {\n${remotionImportList}\n} from "remotion";\n`
      : "";

  return `// Generated by RemotionLab
// Prompt: "${escapedPrompt}"

import React from "react";
${remotionImportBlock}
${exportedCode}
`;
}

/**
 * Generate Root.tsx — Composition setup importing MyComposition.
 */
function generateRootFile(durationInFrames: number, fps: number): string {
  return `import React from "react";
import { Composition } from "remotion";
import { MyComposition } from "./MyComposition";

export const RemotionRoot: React.FC = () => {
  return (
    <Composition
      id="MyComposition"
      component={MyComposition}
      durationInFrames={${durationInFrames}}
      fps={${fps}}
      width={1920}
      height={1080}
    />
  );
};
`;
}

/**
 * Generate index.ts — entry point with registerRoot.
 */
function generateIndexFile(): string {
  return `import { registerRoot } from "remotion";
import { RemotionRoot } from "./Root";

registerRoot(RemotionRoot);
`;
}

/**
 * Generate package.json for the exported Remotion project.
 */
function generatePackageJson(): string {
  const pkg = {
    name: "remotionlab-export",
    version: "1.0.0",
    description: "Remotion video exported from RemotionLab",
    private: true,
    scripts: {
      dev: "npx remotion studio",
      render: "npx remotion render MyComposition out/video.mp4",
      build: "npx remotion bundle",
    },
    dependencies: {
      "@remotion/cli": "^4.0.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      remotion: "^4.0.0",
    },
    devDependencies: {
      "@types/react": "^19",
      typescript: "^5",
    },
  };

  return JSON.stringify(pkg, null, 2) + "\n";
}

/**
 * Generate tsconfig.json for the exported Remotion project.
 */
function generateTsConfig(): string {
  const tsconfig = {
    compilerOptions: {
      target: "ES2018",
      module: "commonjs",
      jsx: "react-jsx",
      strict: true,
      noEmit: true,
      lib: ["es2015"],
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
    },
  };

  return JSON.stringify(tsconfig, null, 2) + "\n";
}

/**
 * Generate remotion.config.ts for the exported Remotion project.
 * Uses @remotion/cli/config import (v4 pattern, NOT "remotion").
 */
function generateRemotionConfig(): string {
  return `import { Config } from "@remotion/cli/config";

Config.setVideoImageFormat("jpeg");
Config.setOverwriteOutput(true);
`;
}
