/**
 * Movie Project Zip Export Generator
 *
 * Produces a complete multi-composition Remotion project scaffold as a zip Blob.
 * The zip contains individual scene files, a MovieComposition using Series,
 * Root with all compositions registered, and standard config files.
 *
 * Structure:
 *   remotionlab-movie-export/
 *     src/Scene01.tsx ... SceneNN.tsx  (individual scene components)
 *     src/MovieComposition.tsx         (Series-based sequential playback)
 *     src/Root.tsx                     (registers all compositions)
 *     src/index.ts                     (entry point with registerRoot)
 *     package.json
 *     tsconfig.json
 *     remotion.config.ts
 */

import JSZip from "jszip";
import { detectUsedAPIs, extractMetadata } from "./export-utils";

interface MovieExportScene {
  rawCode: string;
  name: string;
  durationInFrames: number;
  fps: number;
}

interface MovieExportOptions {
  movieName: string;
  scenes: MovieExportScene[];
  totalDurationInFrames: number;
  fps: number;
}

/**
 * Generate a zip Blob containing a multi-composition Remotion project.
 */
export async function generateMovieProjectZip(
  options: MovieExportOptions
): Promise<Blob> {
  const { movieName, scenes, totalDurationInFrames, fps } = options;

  const zip = new JSZip();
  const root = zip.folder("remotionlab-movie-export")!;
  const src = root.folder("src")!;

  // Generate individual scene files
  const sceneNames: string[] = [];
  for (let i = 0; i < scenes.length; i++) {
    const scene = scenes[i];
    const sceneNum = String(i + 1).padStart(2, "0");
    const sceneName = `Scene${sceneNum}`;
    sceneNames.push(sceneName);

    const content = generateSceneFile(scene.rawCode, sceneName);
    src.file(`${sceneName}.tsx`, content);
  }

  // Generate MovieComposition
  const movieCompContent = generateMovieComposition(
    sceneNames,
    scenes.map((s) => s.durationInFrames)
  );
  src.file("MovieComposition.tsx", movieCompContent);

  // Generate Root with all compositions
  const rootContent = generateRootFile(
    sceneNames,
    scenes,
    totalDurationInFrames,
    fps
  );
  src.file("Root.tsx", rootContent);

  // Generate index.ts
  src.file("index.ts", generateIndexFile());

  // Generate config files
  root.file("package.json", generatePackageJson(movieName));
  root.file("tsconfig.json", generateTsConfig());
  root.file("remotion.config.ts", generateRemotionConfig());

  return zip.generateAsync({ type: "blob" });
}

/**
 * Generate a scene component file from raw code.
 * Detects Remotion imports, strips metadata, renames MyComposition to SceneNN.
 */
function generateSceneFile(rawCode: string, sceneName: string): string {
  const usedAPIs = detectUsedAPIs(rawCode);
  const { cleanedCode } = extractMetadata(rawCode);

  // Rename MyComposition to SceneNN and add export keyword
  const renamedCode = cleanedCode
    .replace(/\bMyComposition\b/g, sceneName)
    .replace(new RegExp(`^const ${sceneName}`, "m"), `export const ${sceneName}`);

  // Build Remotion import block
  const remotionImportBlock =
    usedAPIs.length > 0
      ? `import {\n${usedAPIs.map((a) => `  ${a},`).join("\n")}\n} from "remotion";\n`
      : "";

  return `// Generated by RemotionLab
import React from "react";
${remotionImportBlock}
${renamedCode}
`;
}

/**
 * Generate MovieComposition.tsx using Remotion Series for sequential playback.
 */
function generateMovieComposition(
  sceneNames: string[],
  durations: number[]
): string {
  const imports = sceneNames
    .map((name) => `import { ${name} } from "./${name}";`)
    .join("\n");

  const sequences = sceneNames
    .map(
      (name, i) =>
        `      <Series.Sequence durationInFrames={${durations[i]}}>\n        <${name} />\n      </Series.Sequence>`
    )
    .join("\n");

  return `// Generated by RemotionLab - Movie Composition
import React from "react";
import { Series } from "remotion";
${imports}

export const MovieComposition: React.FC = () => {
  return (
    <Series>
${sequences}
    </Series>
  );
};
`;
}

/**
 * Generate Root.tsx with individual scene compositions + the Movie composition.
 */
function generateRootFile(
  sceneNames: string[],
  scenes: MovieExportScene[],
  totalDurationInFrames: number,
  fps: number
): string {
  const sceneImports = sceneNames
    .map((name) => `import { ${name} } from "./${name}";`)
    .join("\n");

  const sceneCompositions = sceneNames
    .map(
      (name, i) =>
        `      <Composition
        id="${name}"
        component={${name}}
        durationInFrames={${scenes[i].durationInFrames}}
        fps={${fps}}
        width={1920}
        height={1080}
      />`
    )
    .join("\n");

  return `import React from "react";
import { Composition } from "remotion";
import { MovieComposition } from "./MovieComposition";
${sceneImports}

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="Movie"
        component={MovieComposition}
        durationInFrames={${totalDurationInFrames}}
        fps={${fps}}
        width={1920}
        height={1080}
      />
${sceneCompositions}
    </>
  );
};
`;
}

/**
 * Generate index.ts entry point.
 */
function generateIndexFile(): string {
  return `import { registerRoot } from "remotion";
import { RemotionRoot } from "./Root";

registerRoot(RemotionRoot);
`;
}

/**
 * Generate package.json for the movie export project.
 */
function generatePackageJson(movieName: string): string {
  const safeName = movieName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

  const pkg = {
    name: safeName || "remotionlab-movie-export",
    version: "1.0.0",
    description: `Remotion movie exported from RemotionLab: ${movieName}`,
    private: true,
    scripts: {
      dev: "npx remotion studio",
      render: "npx remotion render Movie out/movie.mp4",
      build: "npx remotion bundle",
    },
    dependencies: {
      "@remotion/cli": "^4.0.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      remotion: "^4.0.0",
    },
    devDependencies: {
      "@types/react": "^19",
      typescript: "^5",
    },
  };

  return JSON.stringify(pkg, null, 2) + "\n";
}

/**
 * Generate tsconfig.json for the exported Remotion project.
 */
function generateTsConfig(): string {
  const tsconfig = {
    compilerOptions: {
      target: "ES2018",
      module: "commonjs",
      jsx: "react-jsx",
      strict: true,
      noEmit: true,
      lib: ["es2015"],
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
    },
  };

  return JSON.stringify(tsconfig, null, 2) + "\n";
}

/**
 * Generate remotion.config.ts for the exported Remotion project.
 * Uses @remotion/cli/config import (v4 pattern).
 */
function generateRemotionConfig(): string {
  return `import { Config } from "@remotion/cli/config";

Config.setVideoImageFormat("jpeg");
Config.setOverwriteOutput(true);
`;
}
